# build with:
# $ CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gobut .
# $ docker build -t chooper/gobut -f Dockerfile.scratch .
FROM scratch
ADD cacert.pem /etc/ssl/certs/ca-certificates.crt
ADD gobut /
CMD ["/gobut"]
